version: '3'

services:
  frontend:
    image: slava-bar:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - gateway
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gateway"
      - "traefik.http.routers.bar-frontend.entrypoints=https"
      - "traefik.http.routers.bar-frontend.rule=Host(`calendar.mental-prosvet.ru`)"
      - "traefik.http.routers.bar-frontend.service=bar-frontend-service"
      - "traefik.http.services.bar-frontend-service.loadbalancer.server.port=80"
    environment:
      NODE_ENV: production

networks:
  gateway:
    external: true
    name: proxynet
