version: '3'

services:
  frontend:
    image: slava-bar:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - default
    labels:
      - "traefik.enable=true"  
      - "traefik.docker.network=default"
      - "traefik.http.routers.bar-frontend.entrypoints=websecure"
      - "traefik.http.routers.bar-frontend.rule=Host(`bar.sla2324.fvds.ru`)"
      - "traefik.http.routers.bar-frontend.service=bar-frontend-service"
      - "traefik.http.services.bar-frontend-service.loadbalancer.server.port=80"

networks:
  default:
    name: proxynet
    external: true